"""Render the checked-in permission manifest from the setup-flow contract.

The setup flow is the sole source of truth.  This module deliberately keeps
the JSON and Markdown renderers together so their shared entries cannot drift.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

MANIFEST_SCHEMA_VERSION = 1
JSON_ARTIFACT_NAME = "permissions_manifest.json"
MARKDOWN_ARTIFACT_NAME = "SECURITY_PERMISSIONS.md"


class PermissionsManifestError(ValueError):
    """Raised when the setup-flow source cannot produce a manifest."""


class PermissionsManifestDriftError(AssertionError):
    """Raised when checked-in artifacts differ from their generated bytes."""


@dataclass(frozen=True)
class RenderedPermissionsManifest:
    """The two deterministic artifact byte streams."""

    json_bytes: bytes
    markdown_bytes: bytes


def load_flow(path: Path) -> dict[str, Any]:
    """Load a setup-flow JSON object or fail with its source path."""

    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise PermissionsManifestError(f"unable to read setup flow {path}: {exc}") from exc
    except json.JSONDecodeError as exc:
        raise PermissionsManifestError(f"invalid setup flow JSON {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise PermissionsManifestError(f"setup flow {path} must contain an object")
    return value


def _registry(flow: Mapping[str, Any], name: str) -> Mapping[str, Mapping[str, Any]]:
    value = flow.get(name)
    if not isinstance(value, Mapping):
        raise PermissionsManifestError(f"setup flow has no {name} registry")
    typed: dict[str, Mapping[str, Any]] = {}
    for entry_id, entry in value.items():
        if not isinstance(entry_id, str) or not isinstance(entry, Mapping):
            raise PermissionsManifestError(f"setup flow {name} registry has malformed entry")
        typed[entry_id] = entry
    return typed


def _condition_text(entry: Mapping[str, Any], *, default: str) -> str:
    condition = entry.get("required_when")
    if condition is None:
        return default
    if not isinstance(condition, Mapping):
        raise PermissionsManifestError("required_when must be an object")
    for connective, word in (("any", "or"), ("all", "and")):
        if connective in condition:
            return _compound_condition_text(condition, connective, word, default)
    return _leaf_condition_text(condition)


def _compound_condition_text(condition: Mapping[str, Any], connective: str, word: str, default: str) -> str:
    children = condition[connective]
    if set(condition) != {connective} or not isinstance(children, list) or not children:
        raise PermissionsManifestError("compound required_when must contain a non-empty condition list")
    if not all(isinstance(child, Mapping) for child in children):
        raise PermissionsManifestError("compound required_when children must be objects")
    rendered = [_condition_text({"required_when": child}, default=default)[5:-1] for child in children]
    return "When (" + f") {word} (".join(rendered) + ")."


def _leaf_condition_text(condition: Mapping[str, Any]) -> str:
    decision = condition.get("decision_ref")
    operator = condition.get("operator")
    value = condition.get("value")
    if not isinstance(decision, str) or not isinstance(operator, str) or not isinstance(value, str):
        raise PermissionsManifestError(
            "required_when must contain string decision_ref, operator, and value"
        )
    verbs = {"contains": "contains", "equals": "equals"}
    rendered_operator = verbs.get(operator)
    if rendered_operator is None:
        raise PermissionsManifestError(f"unsupported required_when operator: {operator}")
    return f"When `{decision}` {rendered_operator} `{value}`."


def _permission_entry(entry_id: str, entry: Mapping[str, Any]) -> dict[str, Any]:
    name = _required_string(entry, "name", entry_id)
    return {
        "id": entry_id,
        "entry_type": "permission",
        "what": name,
        "why": _required_string(entry, "purpose", entry_id),
        "when": _condition_text(entry, default="Always required."),
        "denial_behavior": _required_string(entry, "denial_behavior", entry_id),
        "system_settings_pane": entry.get(
            "system_settings_path", "Not applicable (no System Settings path declared)."
        ),
        "grant_actor": _required_string(entry, "grant_actor", entry_id),
        "source": {
            "kind": _required_string(entry, "kind", entry_id),
            "platform": _required_string(entry, "platform", entry_id),
            "grant_operation_ref": entry.get("grant_operation_ref"),
            "probe_ref": _required_string(entry, "probe_ref", entry_id),
            "required_when": entry.get("required_when"),
        },
    }


def _consent_entry(entry_id: str, entry: Mapping[str, Any]) -> dict[str, Any]:
    decline = entry.get("decline")
    if not isinstance(decline, Mapping):
        raise PermissionsManifestError(f"consent {entry_id} has no decline behavior")
    state = _required_string(decline, "state", entry_id)
    consequence = _required_string(decline, "consequence", entry_id)
    required = entry.get("required")
    if not isinstance(required, bool):
        raise PermissionsManifestError(f"consent {entry_id} has no boolean required flag")
    default = (
        "Always required." if required else "Optional; no required_when condition is declared."
    )
    return {
        "id": entry_id,
        "entry_type": "consent",
        "what": _required_string(entry, "title", entry_id),
        "why": _required_string(entry, "prompt", entry_id),
        "when": _condition_text(entry, default=default),
        "denial_behavior": f"Decline state: `{state}`. {consequence}",
        "system_settings_pane": "Not applicable (consent, not a macOS permission entry).",
        "grant_actor": "operator (explicit assent)"
        if entry.get("explicit_assent") is True
        else "Not declared.",
        "source": {
            "category": _required_string(entry, "category", entry_id),
            "scope": _string_list(entry, "scope", entry_id),
            "required": required,
            "required_when": entry.get("required_when"),
            "decline": dict(decline),
        },
    }


def _auth_flow_entry(entry_id: str, entry: Mapping[str, Any]) -> dict[str, Any]:
    start_operations = _string_list(entry, "start_operation_refs", entry_id, required=False)
    default = (
        "No required_when condition is declared; starts through "
        + (", ".join(f"`{operation}`" for operation in start_operations) or "no declared operation")
        + "."
    )
    return {
        "id": entry_id,
        "entry_type": "auth_flow",
        "what": _required_string(entry, "name", entry_id),
        "why": _required_string(entry, "description", entry_id),
        "when": _condition_text(entry, default=default),
        "denial_behavior": "Not declared by this authentication-flow entry.",
        "system_settings_pane": "Not applicable (authentication flow, not a macOS permission entry).",
        "grant_actor": "operator (authentication presence: "
        + _required_string(entry, "operator_presence", entry_id)
        + ").",
        "source": {
            "mode": _required_string(entry, "mode", entry_id),
            "credential_owner": _required_string(entry, "credential_owner", entry_id),
            "start_operation_refs": start_operations,
            "verification_probe_refs": _string_list(
                entry, "verification_probe_refs", entry_id, required=False
            ),
            "required_when": entry.get("required_when"),
        },
    }


def _required_string(entry: Mapping[str, Any], key: str, entry_id: str) -> str:
    value = entry.get(key)
    if not isinstance(value, str) or not value:
        raise PermissionsManifestError(f"{entry_id} has no non-empty {key}")
    return value


def _string_list(
    entry: Mapping[str, Any], key: str, entry_id: str, *, required: bool = True
) -> list[str]:
    value = entry.get(key)
    if value is None and not required:
        return []
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise PermissionsManifestError(f"{entry_id} has no string list {key}")
    return list(value)


def manifest_entries(flow: Mapping[str, Any]) -> list[dict[str, Any]]:
    """Return sorted, normalized entries for every declared trust-surface item."""

    entries: list[dict[str, Any]] = []
    for entry_id, entry in sorted(_registry(flow, "permissions").items()):
        entries.append(_permission_entry(entry_id, entry))
    for entry_id, entry in sorted(_registry(flow, "consents").items()):
        entries.append(_consent_entry(entry_id, entry))
    for entry_id, entry in sorted(_registry(flow, "auth_flows").items()):
        entries.append(_auth_flow_entry(entry_id, entry))
    return entries


def render_manifest(flow: Mapping[str, Any]) -> RenderedPermissionsManifest:
    """Render normalized JSON and reviewer-facing Markdown from ``flow``."""

    source_schema_version = flow.get("schema_version")
    if not isinstance(source_schema_version, int):
        raise PermissionsManifestError("setup flow has no integer schema_version")
    entries = manifest_entries(flow)
    document = {
        "entries": entries,
        "manifest_schema_version": MANIFEST_SCHEMA_VERSION,
        "source_contract": "macos_setup_flow.json",
        "source_contract_schema_version": source_schema_version,
    }
    json_bytes = (json.dumps(document, indent=2, sort_keys=True) + "\n").encode()
    markdown_bytes = _render_markdown(source_schema_version, entries).encode()
    return RenderedPermissionsManifest(json_bytes=json_bytes, markdown_bytes=markdown_bytes)


def _render_markdown(source_schema_version: int, entries: list[dict[str, Any]]) -> str:
    lines = [
        "# Setup security permissions and consents",
        "",
        "This file is generated from `macos_setup_flow.json`; do not edit it by hand.",
        f"Manifest schema version: `{MANIFEST_SCHEMA_VERSION}`.",
        f"Source setup-flow schema version: `{source_schema_version}`.",
        "",
        "It lists the declared setup permission, consent, and authentication-flow surface only.",
        "An item with no declared System Settings pane or denial behavior says so explicitly.",
        "",
    ]
    for entry_type, title in (
        ("permission", "Permissions"),
        ("consent", "Consents"),
        ("auth_flow", "Authentication flows"),
    ):
        lines.extend([f"## {title}", ""])
        for entry in (item for item in entries if item["entry_type"] == entry_type):
            lines.extend(
                [
                    f"### {entry['what']} (`{entry['id']}`)",
                    "",
                    f"- WHAT: {entry['what']}",
                    f"- WHY: {entry['why']}",
                    f"- WHEN: {entry['when']}",
                    f"- WHAT DENIAL DOES: {entry['denial_behavior']}",
                    f"- SYSTEM SETTINGS PANE: {entry['system_settings_pane']}",
                    f"- GRANT ACTOR: {entry['grant_actor']}",
                    "",
                ]
            )
    return "\n".join(lines)


def write_artifacts(flow_path: Path, output_directory: Path) -> RenderedPermissionsManifest:
    """Generate both artifacts below ``output_directory`` from ``flow_path``."""

    rendered = render_manifest(load_flow(flow_path))
    output_directory.mkdir(parents=True, exist_ok=True)
    (output_directory / JSON_ARTIFACT_NAME).write_bytes(rendered.json_bytes)
    (output_directory / MARKDOWN_ARTIFACT_NAME).write_bytes(rendered.markdown_bytes)
    return rendered


def check_artifacts(flow_path: Path, artifact_directory: Path) -> None:
    """Fail loudly when either checked-in artifact is not exactly regenerated."""

    rendered = render_manifest(load_flow(flow_path))
    expected = {
        JSON_ARTIFACT_NAME: rendered.json_bytes,
        MARKDOWN_ARTIFACT_NAME: rendered.markdown_bytes,
    }
    for name, bytes_expected in expected.items():
        path = artifact_directory / name
        try:
            actual = path.read_bytes()
        except OSError as exc:
            raise PermissionsManifestDriftError(
                f"missing generated artifact {path}: {exc}"
            ) from exc
        if actual != bytes_expected:
            raise PermissionsManifestDriftError(
                f"generated artifact drift: {path}; run generate_permissions_manifest.py"
            )
