from enum import StrEnum


class ActionStatus(StrEnum):
    QUEUED = "queued"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    ERROR = "error"


class ErrorType(StrEnum):
    FRAMEWORK_ERROR = "framework_error"
    PLUGIN_ERROR = "plugin_error"
    EXTERNAL_ERROR = "external_error"


class ErrorSeverity(StrEnum):
    DEBUG = "debug"
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class JobStatus(StrEnum):
    """Status values for async job lifecycle."""

    QUEUED = "queued"
    PROCESSING = "processing"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    ERROR = "error"


class ProviderType(StrEnum):
    """Provider types for async jobs."""

    PLUGIN = "plugin"
    SERVICE_INTERFACE = "service_interface"
    EXTERNAL_API = "external_api"


class ProcessorPolicyCategory(StrEnum):
    """Graph theory categories for action processor policy enforcement.

    Pure graph theory terminology for DAG node classification:
    - EDGE: Execution nodes (tools) - do work, route results to VERTEX
    - VERTEX: Decision nodes (inference) - choose next action
    - EDGE_SINK: Terminal nodes - end the flow, never get processors
    """

    EDGE = "edge"
    VERTEX = "vertex"
    EDGE_SINK = "edge_sink"


class ProcessorOrigin(StrEnum):
    """Provenance tracking for processor injection sources.

    Origins enable different policy rules based on processor source:
    - REGISTRY_DEFAULT: From plugin decorator default_result_processor
    - LLM_AUTHORED: Generated by inference action
    - RUNTIME_GENERATED: Created dynamically by system code
    - EXPLICIT_PLAN: Defined in action plan JSON file
    """

    REGISTRY_DEFAULT = "registry_default"
    LLM_AUTHORED = "llm_authored"
    RUNTIME_GENERATED = "runtime_generated"
    EXPLICIT_PLAN = "explicit_plan"


class DistanceMetric(StrEnum):
    """Distance metrics for vector similarity search."""

    COSINE = "cosine"
    EUCLIDEAN = "euclidean"
    DOT_PRODUCT = "dot_product"


class InputType(StrEnum):
    """Input types for embedding generation."""

    TEXT = "text"
    IMAGE = "image"
    AUDIO = "audio"


class SessionStatus(StrEnum):
    """Valid states for a session lifecycle.

    Sessions have only two states:
    - ACTIVE: Session is valid and can receive messages
    - EXPIRED: Session has timed out due to inactivity (90 min default)

    New interactions after expiration create a new session.
    """

    ACTIVE = "active"
    EXPIRED = "expired"


class NamingErrorCode(StrEnum):
    """Error codes for naming validation failures.

    Used by the shared naming utility (ananta/utils/naming.py) for
    type-safe error handling across plugins and services.
    """

    NAME_INVALID = "name_invalid"  # Failed validation (empty, too long, etc.)
    NAME_CONFLICT = "name_conflict"  # external_id already exists
    EXTENSION_INVALID = "extension_invalid"  # Unacceptable for this plugin


class IntentType(StrEnum):
    """Classification types for user intent in discovery service.

    - MAKE_SOMETHING_HAPPEN: All actionable requests (commands AND questions) → run discovery
    - ASK_FOR_CLARIFICATION: Request lacks required details → bypass, ask for clarification
    - CONTINUE_ONGOING_WORK: Approvals and continuations → carry forward prior context
    """

    MAKE_SOMETHING_HAPPEN = "make_something_happen"
    ASK_FOR_CLARIFICATION = "ask_for_clarification"
    CONTINUE_ONGOING_WORK = "continue_ongoing_work"
