class ErrorCode:
    FRAMEWORK_GENERIC = "ananta.framework_generic"
    PLUGIN_GENERIC = "ananta.plugin_generic"
    EXTERNAL_GENERIC = "ananta.external_generic"

    SYSTEM_GENERIC = "ananta.system_generic"
    RESOURCE_GENERIC = "ananta.resource_generic"
    PERMISSION_GENERIC = "ananta.permission_generic"
    VALIDATION_GENERIC = "ananta.validation_generic"
    CONFIGURATION_GENERIC = "ananta.configuration_generic"

    VALIDATION_ERROR = "ananta.validation_error"
    CONFIGURATION_ERROR = "ananta.configuration_error"
    PERMISSION_ERROR = "ananta.permission_error"

    FILE_NOT_FOUND = "ananta.file_not_found"
    FILE_ACCESS_ERROR = "ananta.file_access_error"
    FILE_WRITE_ERROR = "ananta.file_write_error"
    FILE_READ_ERROR = "ananta.file_read_error"

    JSON_PARSE_ERROR = "ananta.json_parse_error"
    JSON_VALIDATION_ERROR = "ananta.json_validation_error"

    PLUGIN_NOT_FOUND = "ananta.plugin_not_found"
    PLUGIN_LOAD_ERROR = "ananta.plugin_load_error"
    PLUGIN_INSTANTIATION_ERROR = "ananta.plugin_instantiation_error"
    PLUGIN_MISSING_METHOD = "ananta.plugin_missing_method"
    PLUGIN_EXECUTION_ERROR = "ananta.plugin_execution_error"
    PLUGIN_INVALID_CLASS = "ananta.plugin_invalid_class"
    PLUGIN_INVALID_INSTANCE = "ananta.plugin_invalid_instance"
    PLUGIN_DUPLICATE_NAME = "ananta.plugin_duplicate_name"
    PLUGIN_OPERATIONAL_CONFIG_ERROR = "ananta.plugin_operational_config_error"
    PLUGIN_OPERATIONAL_CONFIG_MISSING = "ananta.plugin_operational_config_missing"
    PLUGIN_OPERATIONAL_CONFIG_INVALID = "ananta.plugin_operational_config_invalid"
    PLUGIN_CONFIG_ERROR = "ananta.plugin_config_error"

    ACTION_NOT_FOUND = "ananta.action_not_found"
    ACTION_EXECUTION_FAILED = "ananta.action_execution_failed"
    ACTION_INVALID_PARAMS = "ananta.action_invalid_params"
    ACTION_INVALID_FORMAT = "ananta.action_invalid_format"
    ACTION_MISSING_NAME = "ananta.action_missing_name"
    ACTION_MISSING_PLUGIN = "ananta.action_missing_plugin"
    ACTION_PERMISSION_DENIED = "ananta.action_permission_denied"
    ACTION_DEFINITION_NOT_FOUND = "ananta.action_definition_not_found"
    ACTION_PROCESS_NOT_FOUND = "ananta.action_process_not_found"
    ACTION_INVALID_DEFINITION = "ananta.action_invalid_definition"
    ACTION_INVALID_RESPONSE_FORMAT = "ananta.action_invalid_response_format"
    ACTION_INVALID_PARAMETER_TYPE = "ananta.action_invalid_parameter_type"
    ACTION_INVALID_PARAMETERS_TYPE = "ananta.action_invalid_parameters_type"
    ACTION_UNEXPECTED_ERROR = "ananta.action_unexpected_error"
    ACTION_FILE_ACCESS_ERROR = "ananta.action_file_access_error"

    OPERATIONAL_CONFIG_MISSING = "ananta.operational_config_missing"
    OPERATIONAL_CONFIG_INVALID_FORMAT = "ananta.operational_config_invalid_format"
    OPERATIONAL_CONFIG_VALIDATION_ERROR = "ananta.operational_config_validation_error"
    OPERATIONAL_CONFIG_TYPE_ERROR = "ananta.operational_config_type_error"

    NETWORK_GENERIC = "ananta.network_generic"
    TIMEOUT_ERROR = "ananta.timeout_error"

    RUNTIME_ERROR = "ananta.runtime_error"
    ASYNC_ERROR = "ananta.async_error"
    UNKNOWN_ERROR = "ananta.unknown_error"
