"""Type-safe data models for the scheduling plugin.

This module provides Pydantic models for schedule data validation and type safety.
"""

from __future__ import annotations

import datetime
from typing import Any

from pydantic import BaseModel, Field, field_validator

RELOAD_SAFE = True


class ActionData(BaseModel):
    """Represents a single action to be executed."""

    name: str = Field(..., description="Fully qualified process key for the action")
    parameters: dict[str, Any] = Field(
        default_factory=dict, description="Arguments to pass to the action"
    )
    result_processor: dict[str, Any] | None = Field(
        None, description="Optional result processor for chaining actions"
    )
    result_processor_kind: str | None = Field(
        None,
        description=(
            "ResultProcessorKind value (`inference` / `deterministic_continuation` / "
            "`bridge_delivery`) plumbed onto the dispatched action_definition. "
            "EDGE actions: must persist a kind or the ReAct success-path validator "
            "trips RESULT_CONTRACT_VIOLATION (result_processor_kind_missing) per "
            "`contracts.py::_check_result_processor_kind`. EDGE_SINK actions: "
            "omitting the kind is canonical; the dispatcher's EDGE_SINK_SKIP "
            "branch at `action_queue_poller._decide_dispatch` short-circuits when "
            "`result_processor_kind is None and result_processor is None`. Cron "
            "schedules must NOT set this to `inference` because cron-fired actions "
            "have no originating session — the "
            "`<<get_flow_input>>` macro fails with `Empty source_namespace in "
            "flow trigger_data`. The validator in `validation.py` enforces this "
            "scope (inference only); other kinds like `bridge_delivery` route "
            "through structurally distinct paths and are not in the policy set."
        ),
    )

    class Config:
        frozen = True


class ScheduleData(BaseModel):
    """Core schedule information stored in the database."""

    id: str | None = Field(None, description="Unique identifier (auto-generated by StateService)")
    label: str = Field(..., description="Human-readable label for this schedule")
    tags: list[str] = Field(default_factory=list, description="Tags for grouping schedules")
    type: str = Field(..., description="Schedule type: one_time or recurring")
    actions: list[ActionData] = Field(..., description="Actions to execute when triggered")

    # Legacy compatibility
    action_name: str = Field("", description="Legacy single action name")
    action_parameters: dict[str, Any] = Field(
        default_factory=dict, description="Legacy single action parameters"
    )

    # Schedule-type specific fields
    run_at: str | None = Field(None, description="ISO timestamp for one_time schedules")
    cron_expression: str | None = Field(None, description="Cron expression for recurring schedules")

    # Status and context
    status: str = Field("scheduled", description="Current schedule status")
    session_id: str | None = Field(None, description="Session context for action execution")
    flow_id: str | None = Field(None, description="Flow context for action execution")
    error_message: str | None = Field(None, description="Error message if schedule failed")

    @field_validator("type")
    @classmethod
    def validate_type(cls, v: str) -> str:
        """Validate schedule type."""
        if v not in ("one_time", "recurring"):
            raise ValueError(f"Invalid schedule type: {v}. Must be 'one_time' or 'recurring'")
        return v

    @field_validator("run_at")
    @classmethod
    def validate_run_at(cls, v: str | None, info: Any) -> str | None:
        """Validate run_at is provided for one_time schedules."""
        if info.data.get("type") == "one_time" and not v:
            raise ValueError("run_at is required for one_time schedules")
        if v:
            # Validate it's a valid ISO timestamp
            try:
                datetime.datetime.fromisoformat(v)
            except ValueError as e:
                raise ValueError(f"Invalid ISO timestamp for run_at: {v}") from e
        return v

    @field_validator("cron_expression")
    @classmethod
    def validate_cron(cls, v: str | None, info: Any) -> str | None:
        """Validate cron_expression is provided for recurring schedules."""
        if info.data.get("type") == "recurring" and not v:
            raise ValueError("cron_expression is required for recurring schedules")
        return v

    class Config:
        frozen = False  # Allow updates for status changes


class UniversalJobData(BaseModel):
    """Data for the universal asynchronous_jobs table."""

    external_id: str = Field(..., description="Schedule ID linking to plugin's schedule table")
    job_type: str = Field("scheduled_action", description="Type of asynchronous job")
    status: str = Field("pending", description="Job status")
    created_at: str = Field(
        default_factory=lambda: datetime.datetime.now(datetime.UTC).isoformat(),
        description="Job creation timestamp",
    )
    scheduled_at: str | None = Field(None, description="When job is scheduled to run")
    started_at: str | None = Field(None, description="When job execution started")
    completed_at: str | None = Field(None, description="When job execution completed")
    result_data: dict[str, Any] | None = Field(None, description="Job execution result")
    error_message: str | None = Field(None, description="Error message if job failed")

    class Config:
        frozen = False  # Allow updates for status changes
