"""Factory for creating ScheduleData objects.

This module provides a stateless factory class for building and validating
schedule data objects. It extracts the schedule building logic from plugin.py
to provide a clean separation of concerns.
"""

import datetime
from typing import Any

from ..constants import SchedulerJobStatus
from ..models import ActionData, ScheduleData

RELOAD_SAFE = True

_ACTION_ENTRY_FIELDS: frozenset[str] = frozenset(
    {
        "name",
        "parameters",
        "process_key",
        "arguments",
        "result_processor",
        "result_processor_kind",
    }
)


class ScheduleFactory:
    """Factory for creating and validating ScheduleData objects.

    This is a stateless factory that provides pure functions for building
    ScheduleData objects from various input formats. It handles:
    - Parameter extraction from action definitions
    - Schedule type-specific logic (recurring vs one-time)
    - Validation of schedule parameters
    - Building ScheduleData objects with proper defaults
    """

    @staticmethod
    def extract_params(params: dict[str, Any]) -> dict[str, Any]:
        """Extract parameters from action definition.

        Handles both direct parameter format and nested action format:
        - {"action": {"parameters": {...}}} -> extract parameters
        - {"parameters": {...}} -> extract parameters
        - {...} -> use params directly

        Args:
            params: Parameter dictionary from action invocation

        Returns:
            Extracted parameters dictionary
        """
        if isinstance(params, dict) and "action" in params:  # type: ignore[reportUnnecessaryIsInstance]
            action = params["action"]
            if isinstance(action, dict):
                result = action.get("parameters", {})
                return result if isinstance(result, dict) else {}
            return {}
        result = params.get("parameters", params)
        return result if isinstance(result, dict) else {}  # type: ignore[reportUnnecessaryIsInstance]

    @staticmethod
    def create_cron_schedule_data(
        cron_expression: str,
        label: str = "Untitled Schedule",
        tags: list[str] | None = None,
        actions: list[ActionData] | None = None,
        action_name: str = "",
        action_parameters: dict[str, Any] | None = None,
        session_id: str | None = None,
        flow_id: str | None = None,
    ) -> ScheduleData:
        """Create ScheduleData for a recurring (cron) schedule.

        Args:
            cron_expression: Cron expression defining the schedule
            label: Human-readable label for the schedule
            tags: Optional tags for schedule organization
            actions: List of actions to execute (new format)
            action_name: Legacy single action name
            action_parameters: Legacy single action parameters
            session_id: Session context for action execution
            flow_id: Flow context for action execution

        Returns:
            ScheduleData object configured for recurring execution
        """
        return ScheduleData(
            id=None,  # Will be auto-generated by StateService
            label=label,
            tags=tags or [],
            type="recurring",
            cron_expression=cron_expression,
            run_at=None,
            actions=actions or [],
            action_name=action_name,
            action_parameters=action_parameters or {},
            status=SchedulerJobStatus.SCHEDULED,
            session_id=session_id,
            flow_id=flow_id,
            error_message=None,
        )

    @staticmethod
    def create_one_time_schedule_data(
        run_at: datetime.datetime,
        label: str = "Untitled Schedule",
        tags: list[str] | None = None,
        actions: list[ActionData] | None = None,
        action_name: str = "",
        action_parameters: dict[str, Any] | None = None,
        session_id: str | None = None,
        flow_id: str | None = None,
    ) -> ScheduleData:
        """Create ScheduleData for a one-time (delayed) schedule.

        Args:
            run_at: When to execute the schedule
            label: Human-readable label for the schedule
            tags: Optional tags for schedule organization
            actions: List of actions to execute (new format)
            action_name: Legacy single action name
            action_parameters: Legacy single action parameters
            session_id: Session context for action execution
            flow_id: Flow context for action execution

        Returns:
            ScheduleData object configured for one-time execution
        """
        return ScheduleData(
            id=None,  # Will be auto-generated by StateService
            label=label,
            tags=tags or [],
            type="one_time",
            run_at=run_at.isoformat(),
            cron_expression=None,
            actions=actions or [],
            action_name=action_name,
            action_parameters=action_parameters or {},
            status=SchedulerJobStatus.SCHEDULED,
            session_id=session_id,
            flow_id=flow_id,
            error_message=None,
        )

    @staticmethod
    def _reject_unknown_action_fields(action: dict[str, Any]) -> None:
        unknown_fields = sorted(set(action) - _ACTION_ENTRY_FIELDS)
        if unknown_fields:
            raise ValueError(
                f"Unsupported action entry fields: {', '.join(unknown_fields)}"
            )

    @staticmethod
    def _normalized_process_key(action: dict[str, Any]) -> str:
        has_name = "name" in action
        has_process_key = "process_key" in action
        if has_name and has_process_key and action["name"] != action["process_key"]:
            raise ValueError("Action entry has conflicting 'name' and 'process_key'")

        raw_name = action.get("name", action.get("process_key"))
        if not isinstance(raw_name, str) or not raw_name.strip():
            raise ValueError(
                "Each action must include a non-empty string 'name' or 'process_key'"
            )
        return raw_name.strip()

    @staticmethod
    def _normalized_action_parameters(action: dict[str, Any]) -> dict[str, Any]:
        has_parameters = "parameters" in action
        has_arguments = "arguments" in action
        if (
            has_parameters
            and has_arguments
            and action["parameters"] != action["arguments"]
        ):
            raise ValueError(
                "Action entry has conflicting 'parameters' and 'arguments'"
            )

        raw_parameters = action.get("parameters", action.get("arguments", {}))
        if not isinstance(raw_parameters, dict):
            raise ValueError("Action parameters/arguments must be an object")
        return raw_parameters

    @staticmethod
    def _normalize_action_entry(action: dict[str, Any]) -> dict[str, Any]:
        """Validate and normalize canonical/legacy action-entry aliases."""
        ScheduleFactory._reject_unknown_action_fields(action)
        normalized: dict[str, Any] = {
            "name": ScheduleFactory._normalized_process_key(action),
            "parameters": ScheduleFactory._normalized_action_parameters(action),
        }
        if "result_processor" in action:
            normalized["result_processor"] = action["result_processor"]
        if "result_processor_kind" in action:
            normalized["result_processor_kind"] = action["result_processor_kind"]
        return normalized

    @staticmethod
    def _parse_new_format_actions(
        actions_data: Any,
    ) -> tuple[list[ActionData], str, dict[str, Any]]:
        if actions_data is None:
            actions_data = []
        if not isinstance(actions_data, list):
            raise ValueError("actions must be provided as a list")
        if not actions_data:
            raise ValueError(
                "Action definitions must include at least one executable action"
            )

        normalized_actions: list[dict[str, Any]] = []
        for action in actions_data:
            if not isinstance(action, dict):
                raise ValueError("Each action entry must be an object")
            normalized = ScheduleFactory._normalize_action_entry(action)
            normalized_actions.append(normalized)

        actions_list = [ActionData(**action) for action in normalized_actions]
        legacy_action_name = normalized_actions[0].get("name", "") if normalized_actions else ""
        legacy_action_params = normalized_actions[0].get("parameters", {}) if normalized_actions else {}
        return actions_list, legacy_action_name, legacy_action_params

    @staticmethod
    def _parse_memory_tag_actions(
        memory_tag: str,
    ) -> tuple[list[ActionData], str, dict[str, Any]]:
        if not memory_tag.strip():
            raise ValueError("memory_tag must be a non-empty string")

        lookup_params: dict[str, Any] = {
            "tag": memory_tag.strip(),
            "include_archived": False,
        }
        legacy_action_name = "service_interface::memory_service::get_memories_by_tag"
        actions_list = [
            ActionData(
                name=legacy_action_name,
                parameters=lookup_params,
                result_processor=None,
                result_processor_kind=None,
            )
        ]
        return actions_list, legacy_action_name, lookup_params

    @staticmethod
    def _select_action_input(params: dict[str, Any]) -> str:
        """Select one explicit action input or fail on ambiguous/absent modes."""
        action_keys = [
            key
            for key in ("actions", "action_definitions", "action_name")
            if key in params and params[key] is not None
        ]
        has_memory_tag = "memory_tag" in params and params["memory_tag"] is not None

        if len(action_keys) > 1:
            raise ValueError(
                "Provide only one action input: 'action_definitions', 'actions', "
                "or legacy 'action_name'"
            )
        if bool(action_keys) == has_memory_tag:
            raise ValueError(
                "Exactly one of action definitions ('action_definitions' or "
                "'actions') or 'memory_tag' is required"
            )
        return action_keys[0] if action_keys else "memory_tag"

    @staticmethod
    def parse_actions_from_params(
        params: dict[str, Any],
    ) -> tuple[list[ActionData], str, dict[str, Any]]:
        """Parse actions from parameters, supporting both legacy and new formats.

        Supports:
        - New format: {"actions": [{"name": "...", "parameters": {...}}, ...]}
        - Legacy format: {"action_name": "...", "action_parameters": {...}}

        Args:
            params: Extracted parameters dictionary

        Returns:
            Tuple of (actions_list, legacy_action_name, legacy_action_params)

        Raises:
            ValueError: If neither format is provided
        """
        action_input = ScheduleFactory._select_action_input(params)
        if action_input in {"actions", "action_definitions"}:
            return ScheduleFactory._parse_new_format_actions(params[action_input])
        if action_input == "action_name":
            raw_action_name = params.get("action_name")
            if not isinstance(raw_action_name, str) or not raw_action_name.strip():
                raise ValueError("action_name must be a non-empty string")
            legacy_action_name = raw_action_name.strip()
            legacy_action_params = params.get("action_parameters", {})
            if not isinstance(legacy_action_params, dict):
                raise ValueError("action_parameters must be an object")
            actions_list = [
                ActionData(
                    name=legacy_action_name,
                    parameters=legacy_action_params,
                    result_processor=None,
                    result_processor_kind=None,
                )
            ]
            return actions_list, legacy_action_name, legacy_action_params
        memory_tag = params["memory_tag"]
        if not isinstance(memory_tag, str):
            raise ValueError("memory_tag must be a non-empty string")
        return ScheduleFactory._parse_memory_tag_actions(memory_tag)

    @staticmethod
    def parse_delayed_actions_from_params(
        params: dict[str, Any],
    ) -> tuple[list[ActionData], str, dict[str, Any]]:
        """Validate delayed execution mode and content before side effects."""
        parsed = ScheduleFactory.parse_actions_from_params(params)
        if "content" not in params or params["content"] is None:
            return parsed

        content = params["content"]
        if not isinstance(content, str):
            raise ValueError("content must be a string")
        if ScheduleFactory._select_action_input(params) != "memory_tag":
            raise ValueError("content is valid only with memory_tag mode")
        return parsed
